del /q /s *.dcu
del /q /s *.exe
del /q /s *.cbk
del /q /s *.drc
del /q /s *.dsk
del /q /s *.dsm
del /q /s *.identcache
del /q /s *.local
del /q /s *.map
del /q /s *.ico
del /q /s *.dproj
rmdir /Q /S Source\__history
rmdir /Q /S Packages\__history
rmdir /Q /S Library\D2010
rmdir /Q /S Library\DXE4
rmdir /Q /S Library\DXE5
rmdir /Q /S Library\DXE6
rmdir /Q /S Library\DXE7

rmdir /Q /S "Library\Demos\Adapters\__history"
rmdir /Q /S "Library\Demos\AsyncSource\__history"
rmdir /Q /S "Library\Demos\AsyncSource with Filestreams\__history"
rmdir /Q /S "Library\Demos\AsyncTarget\__history"
rmdir /Q /S "Library\Demos\AutoScroll\__history"
rmdir /Q /S "Library\Demos\ComboTargetDemo\__history"
rmdir /Q /S "Library\Demos\CustomFormat1\__history"
rmdir /Q /S "Library\Demos\CustomFormat2\__history"
rmdir /Q /S "Library\Demos\DetailedDemo\__history"
rmdir /Q /S "Library\Demos\ExtractDemo\__history"
rmdir /Q /S "Library\Demos\MultipleTargets\__history"
rmdir /Q /S "Library\Demos\Outlook\__history"
rmdir /Q /S "Library\Demos\OutlookSource\__history"
rmdir /Q /S "Library\Demos\PIDLDemo\__history"
rmdir /Q /S "Library\Demos\RTF\__history"
rmdir /Q /S "Library\Demos\ShellContextMenuHandler\__history"
rmdir /Q /S "Library\Demos\ShellContextMenuHandlerSimple\__history"
rmdir /Q /S "Library\Demos\ShellDragDropHandler\__history"
rmdir /Q /S "Library\Demos\ShellDropHandler\__history"
rmdir /Q /S "Library\Demos\SourceAnalyzer\__history"
rmdir /Q /S "Library\Demos\SourceDemo\__history"
rmdir /Q /S "Library\Demos\TargetAnalyzer\__history"
rmdir /Q /S "Library\Demos\TargetDemo\__history"
rmdir /Q /S "Library\Demos\TreeViewTarget\__history"
rmdir /Q /S "Library\Demos\Unicode\__history"
rmdir /Q /S "Library\Demos\VirtualFile\__history"
rmdir /Q /S "Library\Demos\VirtualFileStream\__history"
rmdir /Q /S "Library\Demos\WM_DROPFILES\__history"
